name: GitGuardian Secret Scan- demo

on:
  push:
  workflow_dispatch:
  
env:
  GITGUARDIAN_API_KEY: ${{ secrets.guardian_token }}
  
jobs:
  security-scan:
    name: Secret scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
       fetch-depth: 0
      
    - name: do GitGuardian Scan
      continue-on-error: true
      run: |
       pip install ggshield
       
       #ggshield auth login --method=token
       #echo "To search for secrets in file "
       #ggshield secret scan path -r .
       echo "To search for secrets in Docker images"
       ggshield secret scan docker nginx 
       
       echo "To search for secrets in repositories"
       ggshield secret scan --json --output result ci
       
       
       #echo "--------To search for secretsin Pypi packages--------"
       #ggshield secret scan pypi flask
       
       #echo "--------To search for vulnerabilities in IaC files use---------"
       #ggshield iac scan .
       
       #for more details run - 
       ggshield secret scan --help 

    - name: GitGuardian scan
      continue-on-error: true
      uses: GitGuardian/ggshield/actions/secret@main
      env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.guardian_token }}
    
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
          name: scan_results
          #path: /home/runner/*/*/*/*.json
          path: result
