name: GitGuardian Secret Scan- demo

on:
  push:
  workflow_dispatch:
  
jobs:
  security-scan:
    name: Secret scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: run GitGuardian Scan
      continue-on-error: true
      run: |
       pip install ggshield
       pip install -U ggshield
       ggshield auth login --token-name ${{ secrets.guardian_token }}
       echo "To search for secrets in file "
       ggshield secret scan path -r .
       
       echo "To search for secrets in repositories"
       ggshield secret scan repo .
       
       echo "To search for secrets in Docker images"
       ggshield secret scan docker nginx 
       
       #echo "--------To search for secretsin Pypi packages--------"
       #ggshield secret scan pypi flask
       
       echo "--------To search for vulnerabilities in IaC files use---------"
       ggshield iac scan .
       
       #for more details run - ggshield secret scan --help 

       
