name: Kics Infrastructure as Code Security Scan- demo

on:
  push:
  workflow_dispatch:
  
jobs:
  Kicks-iac-security:
    name: IAC scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: run kics Scan
      run: |
       wget https://go.dev/dl/go1.18.7.linux-amd64.tar.gz
       sudo rm -rf /usr/local/go
       sudo tar -xzf $GITHUB.WORKSPACE/go1.18.7.linux-amd64.tar.gz
       sudo ls -al
       go version
       cd go1.18.7.linux-amd64
       git clone https://github.com/Checkmarx/kics.git
       cd kics
       make build
       
    # Display the results in json format
    - name: display kics results
      run: |
        cat myResults/results.json
