name: Kics Infrastructure as Code Security Scan- demo

on:
  push:
  workflow_dispatch:
  
jobs:
  Kicks-iac-security:
    name: IAC scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: run kics Scan
      run: |
       wget https://go.dev/dl/go1.19.2.linux-amd64.tar.gz
       sudo tar -C /usr/local -xzf go1.19.2.linux-amd64.tar.gz
       go version
       git clone https://github.com/Checkmarx/kics.git
       cd kics
       make build
       
    # Display the results in json format
    - name: display kics results
      run: |
        cat myResults/results.json
