name: Kics Infrastructure as Code Security Scan- demo

on:
  push:
  workflow_dispatch:
  
jobs:
  Kicks-iac-security:
    name: IAC scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: run kics Scan
      run: |
       docker pull checkmarx/kics:latest
       docker run -u $UID:$GID -v $PWD:/$GITHUB_WORKSPACE checkmarx/kics:ubi8 scan -p $GITHUB_WORKSPACE/terraform -o /$GITHUB_WORKSPACE -v
       wget https://go.dev/dl/go1.18.7.linux-amd64.tar.gz
       sudo rm -rf $GITHUB_WORKSPACE/go
       pwd
       sudo ls -al
       sudo tar -xzf $GITHUB_WORKSPACE/go1.18.7.linux-amd64.tar.gz
       go version
       sudo ls -al
       git clone https://github.com/Checkmarx/kics.git
       cd kics
       make build
       ./bin/kics scan -p '<path-of-your-project-to-scan>' --report-formats json -o ./results
       
    # Display the results in json format
    - name: display kics results
      run: |
        cat myResults/results.json
