name: Kics Infrastructure as Code Security Scan

on:
  push:
  workflow_dispatch:
  
jobs:
  Kicks-iac-security:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Scan Iac with kics
    - name: run kics Scan
      uses: checkmarx/kics-github-action@v1.5
      with:
        # scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
        path: ./terraform/aws/
        output_path: myResults/
        output_formats: json
        ignore-on-exit: results
    # Display the results in json format
    - name: display kics results
      run: |
        cat myResults/results.json
